### ISSUE TITLE
Add 5 day forecast

### ISSUE THREAD

**Issue by marksev1** [fcgdam/ESP8266-OWM-Client#1]
Would you mind adding a 5 day forecast or tell me how I would need to modify the code to get the 5 day forecast instead. Thanks!

**Comment by fcgdam** [comment]
Hi:  According to openweathermap API, the call to weather forecast is defined at: http://openweathermap.org/forecast5.
So, for example for Lisbon, the call URL should be something like: http://api.openweathermap.org/data/2.5/forecast?q=Lisbon&units=metrics&mode=json&appid=2de143494c0b295cca9337e1e96b00e0.

So you should change the line 
conn:send("GET /data/2.5/<b>find</b>?q="..Location.."&units="..Metrics.."&APPID="..OWAPIKEY.."\r\nHTTP/1.1\r\nHost: api.openweathermap.org\r\n".."Connection: keep-alive\r\nAccept: _/_\r\n\r\n") 

to

conn:send("GET /data/2.5/<b>forecast</b>?q="..Location.."&units="..Metrics.."&APPID="..OWAPIKEY.."\r\nHTTP/1.1\r\nHost: api.openweathermap.org\r\n".."Connection: keep-alive\r\nAccept: _/_\r\n\r\n")

The problem now is to process the returned Json Array, but I suppose that all is needed is to cycle the Json output like this:
      MaxTemp_1stDay = record.list[1].main.temp_max
      MinTemp_1stDay = record.list[1].main.temp_min
      MaxTemp_2ndDay = record.list[2].main.temp_max
      MinTemp_2ndDay = record.list[2].main.temp_min

**Comment by marksev1** [comment]
Thanks I'm gonna try that after I get the hardware. And report back the results :).

Also which information is currently displayed and could i expand it? For example I'd really like the description of the weather (like clear sky, rain, cloudy etc. I think its in the json array)

How do you know how to process the array :), where is the marker for the day in the array?

This heap thing, when the esp restarts, how often is that and how much time does it need for restarting and do i need to press anything when it does it (probably it won't bother me just would like to learn the specifics).

Thanks again!

**Comment by fcgdam** [comment]
Hi. Yes you can expand the information. Just need to process the JSON response to get the information that you need. The weather like, Clear, Rain, and so on is already on the Wdesc variable, and it is shown on the LCD.
Regarding the Json data, the array position 1 is for today, 2 for tomorrow and so on.
Regarding the Heap, it was the main reason that I've completely abandoned NodeMcu Lua programming, and switched to Arduino style development with the Sming framework. It will work fine, then reboot, and continue. In this application not an issue.

**Comment by marksev1** [comment]
Cool, thanks! Shall we leave the issue opened just for reference if someone else is interested in the same question as I was?

**Comment by fcgdam** [comment]
Hi: If someone wants to add the 5 day forecast it can fork the repository, and then, maybe, create a pull request.
Anyway, I have doubts that processing the 5 day forecast will work due to the size of the Json response with Nodemcu.
Even this simple client when starting the remaining heap is around 10K, when with Sming framework is around 37K... It's a huge difference.
I can leave it open, but my efforts are on Sming right now, not Lua.

**Comment by marksev1** [comment]
What about displaying just 2 days would that help?

Do you plan on rewriting this with Sming framework?

**Comment by fcgdam** [comment]
The problem is not displaying the data, but processing the JSON response in Lua. It might be too large. I don't know, since I have no esp8266 with nodemcu firmware right now. 
I might give it a go with Sming, just to stress test the Json Library and see how the heap holds out.

**Comment by marksev1** [comment]
What about doing it in Arduino IDE since esp8266 is now supported there :)

**Comment by fcgdam** [comment]
It uses the Arduino IDE... :) Not very good when I'm used to use Netbeans or other real IDE's. Sming is also compatible with Arduino program styles, and you are free to use any IDE available.

**Comment by marksev1** [comment]
So is this Sming framework imported like a library into arduino ide, and then one includes it in sketches and can use it?

**Comment by fcgdam** [comment]
Sming framework is not related to the Arduino IDE. It is a framework on it's own that is compatible with Arduino style programming and libraries. While with ESP8266 Arduino framework, the Arduino IDE is used, the Sming Framework can be used with Netbeans, Eclipse or plain simple make files.
